#!/bin/bash

# Program: chromIDEAS_CSC
package_name="chromIDEAS"
command="chromIDEAS_CSC"
version="1.0"

# define package related path
if true; then
	bin_root=${CONDA_PREFIX}/share/${package_name}/bin
	blacklist_root=${CONDA_PREFIX}/share/${package_name}/blacklist
	genomesize_root=${CONDA_PREFIX}/share/${package_name}/genomesize
	windows_root=${CONDA_PREFIX}/share/${package_name}/bin_windows
	gsl_root=${CONDA_PREFIX}/share/${package_name}/gsl
	manual_root=${CONDA_PREFIX}/share/${package_name}/manuals
fi

# print help
if [[ -z $1 ]]; then
	cat ${manual_root}/${command}.txt
	exit
fi

# get function from config:
# - check_status: check $? and if $? -ne 0, print $1 and execute command $2 (can be null), then exit 100
# - file_check: if ! -f $1, print $1 and exit 100
# - dir_check: if ! -d $1, print $1 and create it
# - getFull_file: print $1 full fileName
# - getFull_dir: if ! -d $1, create $1 and print full dirName, else print $1 full dirName
# - rm_empty: remove empty line in the file
# - data_type: check the input is one of gt0_Integer, 0, Character
if true; then
	source ${bin_root}/CHROMIDEAS_config.sh
fi

# default setting
if true; then
	body_bin_num=10
	length_leveles=10
	file_type=gtf
	location_type=tx
	overlap_cutoff=0.1
	n_HITs=2000
	mode=3
	nthreads=4
	resolutions="0.1-0.9-0.1,1-1.8-0.2,2-5-1"
	clustree=T
fi

# get the arguments
if true; then
	# get arguments from commandline
	while getopts ":hvi:e:r:o:l:z:f:t:O:n:p:m:R:P" opt
	do
		case $opt in
			i) input_CS=${OPTARG} ;;
			e) emission=${OPTARG} ;;
			r) region_file=${OPTARG} ;;
			o) out_prefix=${OPTARG} ;;
			l) body_bin_num=${OPTARG} ;;
			z) length_leveles=${OPTARG} ;;
			f) file_type=${OPTARG} ;;
			t) location_type=${OPTARG} ;;
			O) overlap_cutoff=${OPTARG} ;;
			n) n_HITs=${OPTARG} ;;
			p) nthreads=${OPTARG} ;;
			m) mode=${OPTARG} ;;
			R) resolutions=${OPTARG} ;;
			P) clustree=F ;;

			h) cat ${manual_root}/${command}.txt
			   exit ;;
			v) echo "${package_name} V${version}"
			   exit ;;
			*) echo -e "Invalid option -${OPTARG}\n"
			   exit ;;
		esac
	done
fi

# check the input arguments
if true; then
	# check the required parameters
	if true; then
		if [[ -z ${input_CS} ]] || [[ -z ${emission} ]] || [[ -z ${region_file} ]] || [[ -z ${out_prefix} ]]; then
			echo "Error: Required parameters missing. "
			echo "\tUsage:   chromIDEAS_CSC [options] -i <input_CS> -e <emission> -r <region_file> -o <out_prefix> -f gtf -t tx -O 0.1"
			echo "\t   or:   chromIDEAS_CSC [options] -i <input_CS> -e <emission> -r <region_file> -o <out_prefix> -f gtf -t gene"
			echo "\t   or:   chromIDEAS_CSC [options] -i <input_CS> -e <emission> -r <region_file> -o <out_prefix> -f bed"
			exit 100
		fi
	fi

	# check file: input_CS & emission & region_file
	if true; then
		# input_CS
		if true; then
			# exist?
			if true; then
				file_check ${input_CS}
				input_CS=$(getFull_file ${input_CS})
			fi

			# correct format?
			if true; then
				n=$(head ${input_CS} | awk -F " " '{print NF}' | sort -u)
				if [[ ${n} -lt 5 ]]; then
					echo "Wrong file format for <input_CS>. The file should be space delimited."
					exit 100
				fi
			fi
		fi

		# emission
		if true; then
			# exist?
			if true; then
				file_check ${emission}
				emission=$(getFull_file ${emission})
			fi

			# correct format?
			if true; then
				n=$(head ${emission} | awk -F "\t" '{print NF}' | sort -u)
				if [[ ${n} -lt 4 ]]; then
					echo "Wrong file format for <emission>. The file should be tab delimited and at lease has two markers to define chromatin state."
					exit 100
				fi
			fi
		fi
		
		# region_file
		if true; then
			# exist?
			if true; then
				file_check ${region_file}
				region_file=$(getFull_file ${region_file})
			fi

			# correct format?
			if true; then
				if [[ ${file_type} == "gtf" ]]; then
					n=$(head -n 50 ${region_file} | grep -v "^#" | awk -F "\t" '{print NF}' | sort -u)
					if [[ ${n} -ne 9 ]]; then
						echo "Wrong file format for <region_file>. The standard GTF file format should be a 9-column tab-delimited file."
						exit 100
					fi

					if [[ -z ${location_type} ]] || ( [[ ${location_type} != "gene" ]] && [[ ${location_type} != "tx" ]] ); then
						echo "Error: The '-t' option must be set to either 'gene' or 'tx' when using GTF format."
						exit 100
					fi

					if [[ ${location_type} == "tx" ]]; then
						if ! [[ "${overlap_cutoff}" =~ ^[0-9]+(\.[0-9]+)?$ ]] || (( $(echo "${overlap_cutoff} < 0" | bc -l) )) || (( $(echo "${overlap_cutoff} > 1" | bc -l) )); then
							echo "Error: <overlap_cutoff> must be a number between 0 and 1 (inclusive)."
							exit 101
						fi
					fi
				elif [[ ${file_type} == "bed" ]]; then
					n=$(head -n 10 ${region_file} | awk -F "\t" '{print NF}' | sort -u)
					if [[ ${n} -ne 4 ]]; then
						echo "Wrong file format for <region_file>. The required BED format should contain 4 columns: chrom, chromStart, chromEnd, and strand."
						exit 100
					fi
				fi
			fi
		fi
	fi

	# check directory: out_prefix
	if true; then
		output_dir=$(dirname ${out_prefix})
		output_dir=$(getFull_dir ${output_dir})
		out_prefix=${output_dir}/$(basename ${out_prefix})
	fi

	# change the name
	if [[ ${file_type} == "bed" ]]; then
		location_type="gene"
	fi
fi

# chromIDEAS_CSC
if true; then
	# get variables
	if true; then
		# filename tmp
		if [[ ${file_type} == "bed" ]]; then
			tmp="bed"
			Ttmp="Bed"
		else
			if [[ ${location_type} == "tx" ]]; then
				tmp="tx"
				Ttmp="Tx"
			else
				tmp="gene"
				Ttmp="Gene"
			fi
		fi

		cell1=$(head -n1 ${input_CS} | cut -d " " -f 5)
		cell2=$(head -n1 ${input_CS} | cut -d " " -f 6)
	fi

	cell1_cs_gene="${out_prefix}.${tmp}_Body_${body_bin_num}segments_based_on_CSPercentage.${cell1}.qs"
	cell2_cs_gene="${out_prefix}.${tmp}_Body_${body_bin_num}segments_based_on_CSPercentage.${cell2}.qs"
	HITs="${out_prefix}.${n_HITs}_Highly_Informative_${Ttmp}s.qs"

	# 1. computeCSMat
	if [[ -f ${cell1_cs_gene} && -f {cell2_cs_gene} && -f ${HITs} ]]; then
		echo "(1) The region-segment-wise CS occupancy matrix have been detected, skip the first step calculation."
	else
		echo "(1) Now calculate the region-segment-wise CS occupancy matrix ..."
		computeCSMat -i ${input_CS} \
		-r ${region_file} \
		-o ${out_prefix} \
		-l ${body_bin_num} \
		-z ${length_leveles} \
		-f ${file_type} \
		-t ${location_type} \
		-O ${overlap_cutoff} \
		-n ${n_HITs} \
		-p ${nthreads}
	fi

	# 2.clusterCS
	echo "(2) Now identify functionally coherent chromatin state clusters (CSCs) ..."
	if [[ ${clustree} == T ]]; then
		clusterCS -e ${emission} \
		-a "${cell1_cs_gene}" \
		-b "${cell2_cs_gene}" \
		-H ${HITs} \
		-o ${out_prefix} \
		-m ${mode} \
		-r ${resolutions}
	elif [[ ${clustree} == F ]]; then
		#statements
		clusterCS -e ${emission} \
		-a "${cell1_cs_gene}" \
		-b "${cell2_cs_gene}" \
		-H ${HITs} \
		-o ${out_prefix} \
		-m ${mode} \
		-r ${resolutions} \
		-p
	fi
fi
